apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-veyi
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0023-tenant/tkrw-pr712-0075-0023-app/devfile-sample-veyi@sha256:4075071a419e1add103f6bb66eb371c966e3f1afd8e1c03b7ba2261f0b2cf9d9
        name: my-nodejs
        resources: {}
status: {}
